### ISSUE TITLE
What's New: Google Workspace - Calendar Integration  

### ISSUE THREAD

**Issue by acedward** [Cotalker/documentation#136]
Though a new Step-Bot now Cotalker can be integrated deeply into Google Calendar.
This integration allows to create meetings for any user, and invite any number of external people - only their emails are required

NOTE: This is a company wide integration - google workspace is required.

**Comment by acedward** [comment]
Added documentation to PR 
https://github.com/Cotalker/documentation/pull/131

**Comment by Mauriceac** [comment]
# "New Feature" Preview

![Screen Shot 2021-05-17 at 14 28 20](https://user-images.githubusercontent.com/47286214/118538446-93203800-b724-11eb-8a53-a949f0858f09.png)

**Comment by Mauriceac** [comment]
@acedward 
Questions:
1. What is a valid domain email and how do I get one?
2. The **End Date** field says it accepts either "end date" or "length". But it seems that "length" does not work, only strings in _time and date_ format are accepted. Is this correct?
3. For now, the **Length field** seems obsolete due to the fact that the **End Date** doesn't work without specifying _time_. Is this correct?
4. What is the **Time Zone** field format (GMT or UTC)? What happens if not used? Does it go to GMT +00:00? What happens if the timezone is added to the time format in **Start Date** and **End Date**?

That's it for now...

**Comment by acedward** [comment]
1.  A **valid domain-email** any -real- email that belongs to the google workspace organization. That will be the calendar where the event is created.
2 & 3.  This looks like a bug. Either the rule the end-date or length must be set, but not both. I will fix this.
End-date should only be a date, and lenght a number.
4. TimeZone ithe name, e.g., America/Santiago America/LosAngeles
5.
