### ISSUE TITLE
What's New: MediaFiles API

### ISSUE THREAD

**Issue by rafaelwalter** [Cotalker/documentation#59]

**Comment by Mauriceac** [comment]
# Draft

Users can easily share files through channels and surveys. But administrators should take into consideration the following aspects of file sharing in Cotalker.

:::note
For security reasons, API/V1/FILE has been deprecated.
:::

## Security Features
For security reasons, uploaded files are digitally signed and require user verification in order to be viewed. Only users from the same company can view the uploaded files. In future updates, access to files will be configurable to more limited circles of users.

As a default, verified users will have only 15 minute access to files. Once that time passes, the file must be requested again. Access time is configurable.

## File Formats & Size

**Compatible file formats include:**

| Type | Format |
| --- | ---- |
| videos: | .mpeg, .mpg, .mov, .mp4, .avi |
| images: | .gif, .jpg, .jpeg, png |
| documents: | .xlsx, .xls, .xlsm, .ods, .docx, .doc, .odt, .ppt, .pptx, .odp, .key, .rtf, .pdf, .csv, .ics, .txt, .zip, .log, .md |

**Maximum file size:** 25 MB

## File Upload API

File upload is an asynchronous operation.

`/api/file/upload`

_Upload process:_

| Request | Action |
| ----- | ----- |
| Request 1 | File is uploaded. |
| Request 2 | Loop. Verifies if file upload is ready. |
| Request 3 | Receives file URL. |

#### Example
```typescript
var uploadingFile = api.uploadFile();
var isReady = false;
var uploadedFile;

while (!isReady) {
uploadedFile = api.getFileById(uploadingFile.id);
isReady = uploadedFile.status == 'uploaded';
}

var signedUrl = api.signUrl(uploadedFile.url);
```

## File Request API

Requests file with signature for user verification.

`/api/file/signature`

**Comment by rafaelwalter** [comment]
@Mauriceac algunas mejoras para el ejemplo de upload

``````
const uploadingFile = await api.uploadFile();
let isReady = false;
let uploadedFile;

while (!isReady) {
  // timeout 1s
  await sleep(1000)
  // get file status
  uploadedFile = await api.getFileById(uploadingFile.id);
  // check if ready
  isReady = uploadedFile.status == 'uploaded';
}

const signedUrl = await api.signUrl(uploadedFile.url);
``````

**Comment by acedward** [comment]
@rafaelwalter que va en `const uploadingFile = await api.uploadFile();` un blob ?  referencia a un archivo ?

**Comment by rafaelwalter** [comment]
@acedward tenemos una documentacion openapi de la API de Files, estamos investigando como disponibilizarla para agregar el link desde de la documentacion

**Comment by acedward** [comment]
@rafaelwalter más que nada para el ejemplo poner 

`const uploadingFile = await api.uploadFile(filePath);`

**Comment by rafaelwalter** [comment]
@Mauriceac documentacion OpenAPI de files:
https://dev.cotalker.com//swagger/media/

Acá describe los metodos HTTP, el contenido que se debe mandar, el contenido de respuesta y las rutas.

**Comment by acedward** [comment]
Post api/file/upload dice que no tiene parámetros?

**Comment by rafaelwalter** [comment]
# Input
## Multipart/form-data
Este describe el input del archivo y de un JSON. El archivo se sube como binario con el nombre `file` y el JSON con el nombre `uploadInput`.  

![Screen Shot 2021-04-16 at 3 02 38 PM](https://user-images.githubusercontent.com/26169103/115071926-e3596f80-9ec4-11eb-8be7-3c0c7611df42.png)

## Application/json
Acá podemos ver el schema definition del input JSON que lleva el nombre `uploadInput`  

![Screen Shot 2021-04-16 at 3 02 55 PM](https://user-images.githubusercontent.com/26169103/115071923-e2c0d900-9ec4-11eb-96ae-c66ad35d0972.png)

# Response Schema
Acá vemos tipo de retorno que es la nueva instancia de un `COTFile`  

![Screen Shot 2021-04-16 at 3 03 04 PM](https://user-images.githubusercontent.com/26169103/115071919-e0f71580-9ec4-11eb-986a-6fc90d2babee.png)
