### ISSUE TITLE
Bots versionados

### ISSUE THREAD

**Issue by guillevalin** [Cotalker/documentation#69]
@eduborgono favor conversar con @Mauriceac sobre esta nueva funcionalidad

**Comment by Mauriceac** [comment]
- Mencioné a los "Bots versionados" como "Stage Type Versions". Creo que usar el término "bot" puede llevar a confusiones. Coloqué el tema en la sección **Automations > Routine Builder**.
- Sólo para estar seguro, ¿las versiones también funcionan en las routinas que se crean Workflows y SLAs?
- Agregué la descripción de "Versions" a la tabla de fields en "Routine Builder".

Preview:
----------

### Stage Type Versions

_Stage types_ are actually predefined system bots. Every once in a while, we update these bots, add new features, and improve automations. But, because these changes might affect your existing _routines_ and _bots_, access to older versions are available.

You can see where the _version_ field is located and how versions can have different settings in the following image.

![automations_routines_stage_type_version_00](https://user-images.githubusercontent.com/47286214/115268019-33784200-a110-11eb-92f7-350c6b520b0c.png)

**Comment by acedward** [comment]
@Mauriceac respondiendo estas preguntas:

1. Mencioné a los "Bots versionados" como "Stage Type Versions". Creo que usar el término "bot" puede llevar a confusiones. Coloqué el tema en la sección Automations > Routine Builder.

Creo que stage es muy genérico
Hemos intentado llamar a los "steps" **Routines**

![image](https://user-images.githubusercontent.com/3951895/115751178-ee9a1880-a366-11eb-9e8a-19a673a9842c.png)

Donde una **rutina** es un procedimiento  o está una conjunto de otras **routinas** de ahí el Routine-Builder

2. Sólo para estar seguro, ¿las versiones también funcionan en las routinas que se crean Workflows y SLAs?

Si, en todos - el routine builder es el mismo para todos los tipos de bots/triggers

3. Agregué la descripción de "Versions" a la tabla de fields en "Routine Builder".

Perfecto!

**Comment by Mauriceac** [comment]
1. **Sobre el término "bots versionados".** En este momento el *display* del **Routine Builder** sólo menciona "stage" y "stages". Y el *field* de las versiones hace referencia al Type *field* de la sección "Stages". ¿Van a cambiar el *display*?
